### ISSUE TITLE
Newer version of ltex has been released

### ISSUE THREAD

**Issue by linwaytin** [emacs-languagetool/lsp-ltex#2]
Hi, I noticed the newer version of `ltex-ls` has been released. 
Will it be updated automatically?

**Comment by linwaytin** [comment]
I also found the automatically installed version does not work, which is the one under `.emacs.d/.cache/lsp/ltex-ls/ltex-ls-11.0.0/bin/ltex-ls`.
Is there a way to give the path pointing to my own version?

Thanks.

**Comment by jcs090218** [comment]
Yeah, please set the variable `lsp-ltex-version` to the desire version you want.

```el
(setq lsp-ltex-version "11.0.0")  ; current version
```

Feel free to open a PR for this to became to default. 👍

**Comment by linwaytin** [comment]
Thanks, putting `(setq lsp-ltex-version "12.2.0")` in the `init` block in `use-package` works.
However, the `lsp-ltex` does not activated when I activate `lsp`. 
The lsp server binary is under `.emacs.d/.cache/lsp/lsp-ltex`.
When I ran the binary from the command line, I got
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: LtexLanguageServerLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

My OS is Manjaro Linux, and has jave installed.

**Comment by linwaytin** [comment]
I think I found the problem. `ltex-ls` requires java 11 or higher, and the default version is an older java.
The binary is a bash file, so adding the following
``` bash
JAVA_HOME="/usr/lib/jvm/java-11-openjdk"
```
in the file is a workaround.

**Comment by jcs090218** [comment]
I have mention `JAVA_HOME` in the README, thanks for reporting this issue to us! 👍
